import step1Image from '../images/images/step1.jpg';
import step2Image from '../images/images/step2.jpg';
import step3Image from '../images/images/step3.jpg';
import step4Image from '../images/images/step4.jpg';

// Static data for cuisine types and daily inspiration
export const cuisineTypes = [
  { name: "Chinese", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=400&fit=crop" },
  { name: "Italian", image: "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=400&h=400&fit=crop" },
  { name: "Japanese", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=400&fit=crop" },
  { name: "Lebanese", image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=400&fit=crop" },
  { name: "Mexican", image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=400&fit=crop" },
  { name: "Indian", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=400&fit=crop" },
  { name: "Thai", image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=400&fit=crop" },
  { name: "French", image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=400&fit=crop" },
];

export const dailyInspiration = [
  { name: "Taco", image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=400&fit=crop" },
  { name: "Jiaozi", image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=400&fit=crop" },
  { name: "Pad Thai", image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=400&fit=crop" },
  { name: "Risotto", image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=400&fit=crop" },
  { name: "Sushi", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=400&fit=crop" },
  { name: "Falafel", image: "https://images.unsplash.com/photo-1547058881-aa0edd92aab3?auto=format&fit=crop&w=400&q=80" },
  { name: "Ramen", image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=400&fit=crop" },
  { name: "Paella", image: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=400&h=400&fit=crop" },
];

export const sampleRecipes = [
  {
    id: "demo-lb-2",
    title: "Lamb Kafta with Tahini",
    description: "Hand-rolled spiced lamb kafta skewers served with creamy tahini sauce and warm flatbread.",
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
    cuisine: "Lebanese",
    protein_type: "lamb",
    cooking_time: 35,
    portions: 4,
    tags: ["Dinner", "Grilled", "Lamb"],
    ingredients: [
      { name: "Ground lamb", amount: "500g", notes: "" },
      { name: "Yellow onion", amount: "1 medium", notes: "grated" },
      { name: "Fresh parsley", amount: "1/2 cup", notes: "finely chopped" },
      { name: "Allspice", amount: "1 tsp", notes: "" },
      { name: "Cinnamon", amount: "1/2 tsp", notes: "" },
      { name: "Cumin", amount: "1/2 tsp", notes: "" },
      { name: "Salt", amount: "1 tsp", notes: "" },
      { name: "Tahini", amount: "1/2 cup", notes: "" },
      { name: "Lemon juice", amount: "3 tbsp", notes: "fresh" },
      { name: "Garlic", amount: "1 clove", notes: "crushed" },
      { name: "Water", amount: "3 tbsp", notes: "to thin tahini" },
      { name: "Flatbread", amount: "4", notes: "to serve" },
    ],
    steps: [
      { instruction: "Combine ground lamb, grated onion, parsley, allspice, cinnamon, cumin, and salt. Mix well.", duration_minutes: 5 },
      { instruction: "With wet hands, shape the mixture around skewers into long oval patties.", duration_minutes: 8 },
      { instruction: "Refrigerate for 15 minutes to help them hold their shape.", duration_minutes: 15 },
      { instruction: "Whisk tahini, lemon juice, garlic, and water together until smooth and creamy.", duration_minutes: 3 },
      { instruction: "Grill kafta over high heat for 3-4 minutes per side until nicely charred.", duration_minutes: 8 },
      { instruction: "Warm the flatbread on the grill for 30 seconds.", duration_minutes: 1 },
      { instruction: "Serve kafta drizzled with tahini sauce on warm flatbread.", duration_minutes: 2 },
    ],
  },
  {
    id: "demo-lb-3",
    title: "Lebanese Fattoush Salad",
    description: "A bright, crunchy salad of fresh herbs, vegetables, and toasted pita with sumac dressing.",
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
    cuisine: "Lebanese",
    protein_type: "vegetarian",
    cooking_time: 15,
    portions: 3,
    tags: ["Lebanese", "Quick", "Lunch", "Healthy", "Vegetarian"],
    ingredients: [
      { name: "Pita bread", amount: "2", notes: "torn into pieces" },
      { name: "Romaine lettuce", amount: "1 head", notes: "chopped" },
      { name: "Cherry tomatoes", amount: "1 cup", notes: "halved" },
      { name: "Cucumber", amount: "1", notes: "diced" },
      { name: "Radishes", amount: "5", notes: "sliced" },
      { name: "Fresh mint", amount: "1/4 cup", notes: "roughly torn" },
      { name: "Fresh parsley", amount: "1/4 cup", notes: "roughly chopped" },
      { name: "Sumac", amount: "2 tsp", notes: "" },
      { name: "Lemon juice", amount: "3 tbsp", notes: "" },
      { name: "Olive oil", amount: "3 tbsp", notes: "" },
      { name: "Salt", amount: "to taste", notes: "" },
    ],
    steps: [
      { instruction: "Brush pita pieces with olive oil and toast in a pan or oven until golden and crispy.", duration_minutes: 5 },
      { instruction: "Combine lettuce, tomatoes, cucumber, radishes, mint, and parsley in a large bowl.", duration_minutes: 4 },
      { instruction: "Whisk together lemon juice, olive oil, sumac, and salt for the dressing.", duration_minutes: 2 },
      { instruction: "Toss the salad with the dressing just before serving.", duration_minutes: 1 },
      { instruction: "Add the toasted pita pieces on top so they stay crunchy.", duration_minutes: 1 },
    ],
  },
  {
    id: "lebanesechickenandrice",
    title: "Lebanese Chicken and Rice",
    description: "A fragrant and spicy chicken dish with warm Middle Eastern spices, served over fluffy rice.",
    image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=600&fit=crop",
    cuisine: "Lebanese",
    protein_type: "chicken",
    cooking_time: 45,
    portions: 2,
    tags: ["Lebanese", "Chicken"],
    ingredients: [
      { name: "Chicken thighs", amount: "400g", notes: "" },
      { name: "White rice", amount: "190g", notes: "" },
      { name: "Water", amount: "380ml", notes: "for cooking rice" },
      { name: "Garlic", amount: "2 cloves", notes: "" },
      { name: "Yellow onion", amount: "1 large", notes: "" },
      { name: "Lemon", amount: "1", notes: "fresh" },
      { name: "Olive oil", amount: "2 tbsp", notes: "" },
      { name: "Fresh parsley", amount: "1/4 cup", notes: "chopped" },
      { name: "Salt", amount: "to taste", notes: "" },
      { name: "Black pepper", amount: "to taste", notes: "" },
      { name: "Lebanese Spices", amount: "1/2 tsp each", notes: "cumin, coriander, cinnamon, turmeric" },
    ],
    steps: [
      { instruction: "Rinse the rice, cook the water. Bring to boil, then cover and turn the heat to low for 30 minutes.", duration_minutes: 30},
      { 
        instruction: "Debone the chicken.", 
        duration_minutes: 15,
        guide: {
          title: "How to Debone Chicken",
          steps: [
            { 
              image: step1Image, 
              caption: "Locate the bone and make a shallow cut along its length to expose it." 
            },
            { 
              image: step2Image, 
              caption: "Carefully cut around both joints at the ends to loosen the bone." 
            },
            { 
              image: step3Image, 
              caption: "Slide the knife under the bone and lift it away from the meat." 
            },
            { 
              image: step4Image, 
              caption: "Trim any excess cartilage for a perfectly clean, boneless thigh." 
            }
          ]
        }
      },
      { instruction: "Cut the onion.", duration_minutes: 2},
      { instruction: "Heat oil in the pan and put in the chopped onion.", duration_minutes: 3 },
      { instruction: "Add your seasoning: a pinch of salt, pepper, and a teaspoon each of cumin, coriander, and cinnamon.", duration_minutes: 1 },
      { instruction: "Stir for 1 minute.", duration_minutes: 1 },
      { instruction: "Push the onions to the side and place your chicken thighs in the pan", duration_minutes: 2 },
      { instruction: "Put the other half in a container once it cools.", duration_minutes: 1},
    ],
  },
  {
    id: "demo-lb-4",
    title: "Lemon Garlic Chicken Shawarma",
    description: "Tender marinated chicken with warm spices, wrapped in flatbread with garlic sauce and pickles.",
    image_url: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=800&h=600&fit=crop",
    cuisine: "Lebanese",
    protein_type: "chicken",
    cooking_time: 40,
    portions: 4,
    tags: ["Dinner", "Street Food", "Chicken"],
    ingredients: [
      { name: "Chicken thighs", amount: "700g", notes: "boneless" },
      { name: "Yogurt", amount: "3 tbsp", notes: "" },
      { name: "Lemon juice", amount: "3 tbsp", notes: "" },
      { name: "Garlic", amount: "5 cloves", notes: "minced" },
      { name: "Cumin", amount: "1 tsp", notes: "" },
      { name: "Turmeric", amount: "1/2 tsp", notes: "" },
      { name: "Coriander", amount: "1 tsp", notes: "ground" },
      { name: "Paprika", amount: "1 tsp", notes: "" },
      { name: "Olive oil", amount: "2 tbsp", notes: "" },
      { name: "Flatbread", amount: "4", notes: "" },
      { name: "Garlic sauce (toum)", amount: "4 tbsp", notes: "" },
      { name: "Pickled turnips", amount: "1/2 cup", notes: "" },
    ],
    steps: [
      { instruction: "Mix yogurt, lemon juice, garlic, cumin, turmeric, coriander, paprika, and olive oil into a marinade.", duration_minutes: 4 },
      { instruction: "Coat the chicken thighs in the marinade and let rest for at least 20 minutes.", duration_minutes: 20 },
      { instruction: "Heat a grill pan or skillet over high heat.", duration_minutes: 2 },
      { instruction: "Cook chicken for 5-6 minutes per side until charred and cooked through.", duration_minutes: 12 },
      { instruction: "Rest the chicken for 3 minutes then slice thinly.", duration_minutes: 3 },
      { instruction: "Warm the flatbread. Spread garlic sauce, add sliced chicken and pickled turnips.", duration_minutes: 3 },
    ],
  },
  {
    id: "demo-2",
    title: "Crispy Fish Tacos",
    description: "Light and crispy beer-battered fish with tangy slaw, wrapped in warm corn tortillas.",
    image_url: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=600&fit=crop",
    cuisine: "Mexican",
    protein_type: "fish",
    cooking_time: 30,
    portions: 3,
    tags: ["Quick", "Lunch", "Fish"],
    ingredients: [
      { name: "White fish fillets", amount: "400g", notes: "cod or tilapia" },
      { name: "Corn tortillas", amount: "8", notes: "small" },
      { name: "Cabbage", amount: "2 cups", notes: "shredded" },
      { name: "Lime", amount: "2", notes: "" },
      { name: "Sour cream", amount: "1/2 cup", notes: "" },
      { name: "Flour", amount: "1 cup", notes: "" },
      { name: "Beer", amount: "3/4 cup", notes: "light lager" },
      { name: "Avocado", amount: "1", notes: "sliced" },
      { name: "Cilantro", amount: "1/4 cup", notes: "fresh" },
      { name: "Salt", amount: "to taste", notes: "" },
    ],
    steps: [
      { instruction: "Mix flour, beer, and a pinch of salt to create a smooth batter. Let it rest for 10 minutes.", duration_minutes: 12 },
      { instruction: "Cut the fish fillets into strips about 2 inches wide.", duration_minutes: 3 },
      { instruction: "Heat oil in a deep pan to 375°F (190°C).", duration_minutes: 5 },
      { instruction: "Dip each fish strip into the batter, letting excess drip off, and carefully lower into the hot oil.", duration_minutes: 2 },
      { instruction: "Fry for 3-4 minutes until golden and crispy. Drain on paper towels.", duration_minutes: 4 },
      { instruction: "Warm the corn tortillas in a dry skillet for 30 seconds each side.", duration_minutes: 3 },
      { instruction: "Toss the shredded cabbage with lime juice and a pinch of salt.", duration_minutes: 2 },
      { instruction: "Assemble tacos: tortilla, cabbage slaw, crispy fish, avocado slices, sour cream, and cilantro.", duration_minutes: 3 },
    ],
  },
  {
    id: "demo-3",
    title: "Vegetable Stir Fry",
    description: "A colorful medley of fresh vegetables wok-tossed in a savory ginger-soy sauce.",
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop",
    cuisine: "Chinese",
    protein_type: "vegetarian",
    cooking_time: 15,
    portions: 2,
    tags: ["Quick", "Healthy", "Vegetarian"],
    ingredients: [
      { name: "Broccoli", amount: "1 cup", notes: "florets" },
      { name: "Bell pepper", amount: "1", notes: "sliced" },
      { name: "Carrots", amount: "2", notes: "julienned" },
      { name: "Snow peas", amount: "1 cup", notes: "" },
      { name: "Soy sauce", amount: "3 tbsp", notes: "" },
      { name: "Sesame oil", amount: "1 tbsp", notes: "" },
      { name: "Ginger", amount: "1 inch", notes: "grated" },
      { name: "Garlic", amount: "3 cloves", notes: "minced" },
      { name: "Cornstarch", amount: "1 tsp", notes: "mixed with 2 tbsp water" },
      { name: "Sesame seeds", amount: "1 tbsp", notes: "for garnish" },
    ],
    steps: [
      { instruction: "Prepare all vegetables: cut broccoli into florets, slice bell pepper, julienne carrots, and trim snow peas.", duration_minutes: 5 },
      { instruction: "Heat sesame oil in a wok over high heat until smoking.", duration_minutes: 1 },
      { instruction: "Add ginger and garlic, stir fry for 30 seconds until fragrant.", duration_minutes: 1 },
      { instruction: "Add carrots and broccoli first — they take longest. Stir fry for 2 minutes.", duration_minutes: 2 },
      { instruction: "Add bell pepper and snow peas. Toss everything together for another 2 minutes.", duration_minutes: 2 },
      { instruction: "Pour in soy sauce and cornstarch mixture. Toss to coat evenly.", duration_minutes: 1 },
      { instruction: "Cook for 1 more minute until the sauce thickens and glazes the vegetables.", duration_minutes: 1 },
      { instruction: "Serve immediately topped with sesame seeds.", duration_minutes: 1 },
    ],
  },
  {
    id: "demo-4",
    title: "Classic Beef Burger",
    description: "Juicy hand-formed beef patties with caramelized onions and melted cheese on brioche buns.",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop",
    cuisine: "American",
    protein_type: "beef",
    cooking_time: 25,
    portions: 4,
    tags: ["Dinner", "Classic", "Beef"],
    ingredients: [
      { name: "Ground beef", amount: "500g", notes: "80/20 blend" },
      { name: "Brioche buns", amount: "4", notes: "" },
      { name: "Cheddar cheese", amount: "4 slices", notes: "" },
      { name: "Yellow onion", amount: "2", notes: "sliced into rings" },
      { name: "Lettuce", amount: "4 leaves", notes: "butter lettuce" },
      { name: "Tomato", amount: "1 large", notes: "sliced" },
      { name: "Pickles", amount: "8 slices", notes: "" },
      { name: "Salt", amount: "to taste", notes: "" },
      { name: "Black pepper", amount: "to taste", notes: "" },
      { name: "Butter", amount: "2 tbsp", notes: "" },
    ],
    steps: [
      { instruction: "Divide the ground beef into 4 equal portions and gently form into patties. Season with salt and pepper.", duration_minutes: 3 },
      { instruction: "Melt butter in a skillet over medium heat. Add onion rings and cook slowly until caramelized, about 10 minutes.", duration_minutes: 10 },
      { instruction: "Heat a grill or cast-iron pan to high heat.", duration_minutes: 2 },
      { instruction: "Cook patties for 3-4 minutes per side for medium. Add cheese in the last minute and cover to melt.", duration_minutes: 8 },
      { instruction: "Toast the brioche buns on the grill for 30 seconds.", duration_minutes: 1 },
      { instruction: "Assemble: bottom bun, lettuce, patty with cheese, caramelized onions, tomato, pickles, top bun.", duration_minutes: 2 },
    ],
  },
];